// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DareFightingICE.Grpc.Proto {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgdzZXJ2aWNlKlIKCEdycGNGbGFnEgkKBUVNUFRZEAAS",
            "DgoKSU5JVElBTElaRRABEg4KClBST0NFU1NJTkcQAhINCglST1VORF9FTkQQ",
            "AxIMCghHQU1FX0VORBAEKk0KCUdycGNTdGF0ZRIPCgtTVEFORF9TVEFURRAA",
            "EhAKDENST1VDSF9TVEFURRABEg0KCUFJUl9TVEFURRACEg4KCkRPV05fU1RB",
            "VEUQAyrZBgoKR3JwY0FjdGlvbhILCgdORVVUUkFMEAASCQoFU1RBTkQQARIQ",
            "CgxGT1JXQVJEX1dBTEsQAhIICgREQVNIEAMSDQoJQkFDS19TVEVQEAQSCgoG",
            "Q1JPVUNIEAUSCAoESlVNUBAGEgwKCEZPUl9KVU1QEAcSDQoJQkFDS19KVU1Q",
            "EAgSBwoDQUlSEAkSDwoLU1RBTkRfR1VBUkQQChIQCgxDUk9VQ0hfR1VBUkQQ",
            "CxINCglBSVJfR1VBUkQQDBIVChFTVEFORF9HVUFSRF9SRUNPVhANEhYKEkNS",
            "T1VDSF9HVUFSRF9SRUNPVhAOEhMKD0FJUl9HVUFSRF9SRUNPVhAPEg8KC1NU",
            "QU5EX1JFQ09WEBASEAoMQ1JPVUNIX1JFQ09WEBESDQoJQUlSX1JFQ09WEBIS",
            "DwoLQ0hBTkdFX0RPV04QExIICgRET1dOEBQSCAoEUklTRRAVEgsKB0xBTkRJ",
            "TkcQFhILCgdUSFJPV19BEBcSCwoHVEhST1dfQhAYEg0KCVRIUk9XX0hJVBAZ",
            "EhAKDFRIUk9XX1NVRkZFUhAaEgsKB1NUQU5EX0EQGxILCgdTVEFORF9CEBwS",
            "DAoIQ1JPVUNIX0EQHRIMCghDUk9VQ0hfQhAeEgkKBUFJUl9BEB8SCQoFQUlS",
            "X0IQIBIKCgZBSVJfREEQIRIKCgZBSVJfREIQIhIMCghTVEFORF9GQRAjEgwK",
            "CFNUQU5EX0ZCECQSDQoJQ1JPVUNIX0ZBECUSDQoJQ1JPVUNIX0ZCECYSCgoG",
            "QUlSX0ZBECcSCgoGQUlSX0ZCECgSCgoGQUlSX1VBECkSCgoGQUlSX1VCECoS",
            "EQoNU1RBTkRfRF9ERl9GQRArEhEKDVNUQU5EX0RfREZfRkIQLBIRCg1TVEFO",
            "RF9GX0RfREZBEC0SEQoNU1RBTkRfRl9EX0RGQhAuEhEKDVNUQU5EX0RfREJf",
            "QkEQLxIRCg1TVEFORF9EX0RCX0JCEDASDwoLQUlSX0RfREZfRkEQMRIPCgtB",
            "SVJfRF9ERl9GQhAyEg8KC0FJUl9GX0RfREZBEDMSDwoLQUlSX0ZfRF9ERkIQ",
            "NBIPCgtBSVJfRF9EQl9CQRA1Eg8KC0FJUl9EX0RCX0JCEDYSEQoNU1RBTkRf",
            "RF9ERl9GQxA3Qh2qAhpEYXJlRmlnaHRpbmdJQ0UuR3JwYy5Qcm90b2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DareFightingICE.Grpc.Proto.GrpcFlag), typeof(global::DareFightingICE.Grpc.Proto.GrpcState), typeof(global::DareFightingICE.Grpc.Proto.GrpcAction), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GrpcFlag {
    [pbr::OriginalName("EMPTY")] Empty = 0,
    [pbr::OriginalName("INITIALIZE")] Initialize = 1,
    [pbr::OriginalName("PROCESSING")] Processing = 2,
    [pbr::OriginalName("ROUND_END")] RoundEnd = 3,
    [pbr::OriginalName("GAME_END")] GameEnd = 4,
  }

  public enum GrpcState {
    [pbr::OriginalName("STAND_STATE")] StandState = 0,
    [pbr::OriginalName("CROUCH_STATE")] CrouchState = 1,
    [pbr::OriginalName("AIR_STATE")] AirState = 2,
    [pbr::OriginalName("DOWN_STATE")] DownState = 3,
  }

  public enum GrpcAction {
    [pbr::OriginalName("NEUTRAL")] Neutral = 0,
    [pbr::OriginalName("STAND")] Stand = 1,
    [pbr::OriginalName("FORWARD_WALK")] ForwardWalk = 2,
    [pbr::OriginalName("DASH")] Dash = 3,
    [pbr::OriginalName("BACK_STEP")] BackStep = 4,
    [pbr::OriginalName("CROUCH")] Crouch = 5,
    [pbr::OriginalName("JUMP")] Jump = 6,
    [pbr::OriginalName("FOR_JUMP")] ForJump = 7,
    [pbr::OriginalName("BACK_JUMP")] BackJump = 8,
    [pbr::OriginalName("AIR")] Air = 9,
    [pbr::OriginalName("STAND_GUARD")] StandGuard = 10,
    [pbr::OriginalName("CROUCH_GUARD")] CrouchGuard = 11,
    [pbr::OriginalName("AIR_GUARD")] AirGuard = 12,
    [pbr::OriginalName("STAND_GUARD_RECOV")] StandGuardRecov = 13,
    [pbr::OriginalName("CROUCH_GUARD_RECOV")] CrouchGuardRecov = 14,
    [pbr::OriginalName("AIR_GUARD_RECOV")] AirGuardRecov = 15,
    [pbr::OriginalName("STAND_RECOV")] StandRecov = 16,
    [pbr::OriginalName("CROUCH_RECOV")] CrouchRecov = 17,
    [pbr::OriginalName("AIR_RECOV")] AirRecov = 18,
    [pbr::OriginalName("CHANGE_DOWN")] ChangeDown = 19,
    [pbr::OriginalName("DOWN")] Down = 20,
    [pbr::OriginalName("RISE")] Rise = 21,
    [pbr::OriginalName("LANDING")] Landing = 22,
    [pbr::OriginalName("THROW_A")] ThrowA = 23,
    [pbr::OriginalName("THROW_B")] ThrowB = 24,
    [pbr::OriginalName("THROW_HIT")] ThrowHit = 25,
    [pbr::OriginalName("THROW_SUFFER")] ThrowSuffer = 26,
    [pbr::OriginalName("STAND_A")] StandA = 27,
    [pbr::OriginalName("STAND_B")] StandB = 28,
    [pbr::OriginalName("CROUCH_A")] CrouchA = 29,
    [pbr::OriginalName("CROUCH_B")] CrouchB = 30,
    [pbr::OriginalName("AIR_A")] AirA = 31,
    [pbr::OriginalName("AIR_B")] AirB = 32,
    [pbr::OriginalName("AIR_DA")] AirDa = 33,
    [pbr::OriginalName("AIR_DB")] AirDb = 34,
    [pbr::OriginalName("STAND_FA")] StandFa = 35,
    [pbr::OriginalName("STAND_FB")] StandFb = 36,
    [pbr::OriginalName("CROUCH_FA")] CrouchFa = 37,
    [pbr::OriginalName("CROUCH_FB")] CrouchFb = 38,
    [pbr::OriginalName("AIR_FA")] AirFa = 39,
    [pbr::OriginalName("AIR_FB")] AirFb = 40,
    [pbr::OriginalName("AIR_UA")] AirUa = 41,
    [pbr::OriginalName("AIR_UB")] AirUb = 42,
    [pbr::OriginalName("STAND_D_DF_FA")] StandDDfFa = 43,
    [pbr::OriginalName("STAND_D_DF_FB")] StandDDfFb = 44,
    [pbr::OriginalName("STAND_F_D_DFA")] StandFDDfa = 45,
    [pbr::OriginalName("STAND_F_D_DFB")] StandFDDfb = 46,
    [pbr::OriginalName("STAND_D_DB_BA")] StandDDbBa = 47,
    [pbr::OriginalName("STAND_D_DB_BB")] StandDDbBb = 48,
    [pbr::OriginalName("AIR_D_DF_FA")] AirDDfFa = 49,
    [pbr::OriginalName("AIR_D_DF_FB")] AirDDfFb = 50,
    [pbr::OriginalName("AIR_F_D_DFA")] AirFDDfa = 51,
    [pbr::OriginalName("AIR_F_D_DFB")] AirFDDfb = 52,
    [pbr::OriginalName("AIR_D_DB_BA")] AirDDbBa = 53,
    [pbr::OriginalName("AIR_D_DB_BB")] AirDDbBb = 54,
    [pbr::OriginalName("STAND_D_DF_FC")] StandDDfFc = 55,
  }

  #endregion

}

#endregion Designer generated code
