// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DareFightingICE.Grpc.Proto {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgdzZXJ2aWNlKikKDkdycGNTdGF0dXNDb2RlEgsKB1NV",
            "Q0NFU1MQABIKCgZGQUlMRUQQASpSCghHcnBjRmxhZxIJCgVFTVBUWRAAEg4K",
            "CklOSVRJQUxJWkUQARIOCgpQUk9DRVNTSU5HEAISDQoJUk9VTkRfRU5EEAMS",
            "DAoIR0FNRV9FTkQQBCpNCglHcnBjU3RhdGUSDwoLU1RBTkRfU1RBVEUQABIQ",
            "CgxDUk9VQ0hfU1RBVEUQARINCglBSVJfU1RBVEUQAhIOCgpET1dOX1NUQVRF",
            "EAMq2QYKCkdycGNBY3Rpb24SCwoHTkVVVFJBTBAAEgkKBVNUQU5EEAESEAoM",
            "Rk9SV0FSRF9XQUxLEAISCAoEREFTSBADEg0KCUJBQ0tfU1RFUBAEEgoKBkNS",
            "T1VDSBAFEggKBEpVTVAQBhIMCghGT1JfSlVNUBAHEg0KCUJBQ0tfSlVNUBAI",
            "EgcKA0FJUhAJEg8KC1NUQU5EX0dVQVJEEAoSEAoMQ1JPVUNIX0dVQVJEEAsS",
            "DQoJQUlSX0dVQVJEEAwSFQoRU1RBTkRfR1VBUkRfUkVDT1YQDRIWChJDUk9V",
            "Q0hfR1VBUkRfUkVDT1YQDhITCg9BSVJfR1VBUkRfUkVDT1YQDxIPCgtTVEFO",
            "RF9SRUNPVhAQEhAKDENST1VDSF9SRUNPVhAREg0KCUFJUl9SRUNPVhASEg8K",
            "C0NIQU5HRV9ET1dOEBMSCAoERE9XThAUEggKBFJJU0UQFRILCgdMQU5ESU5H",
            "EBYSCwoHVEhST1dfQRAXEgsKB1RIUk9XX0IQGBINCglUSFJPV19ISVQQGRIQ",
            "CgxUSFJPV19TVUZGRVIQGhILCgdTVEFORF9BEBsSCwoHU1RBTkRfQhAcEgwK",
            "CENST1VDSF9BEB0SDAoIQ1JPVUNIX0IQHhIJCgVBSVJfQRAfEgkKBUFJUl9C",
            "ECASCgoGQUlSX0RBECESCgoGQUlSX0RCECISDAoIU1RBTkRfRkEQIxIMCghT",
            "VEFORF9GQhAkEg0KCUNST1VDSF9GQRAlEg0KCUNST1VDSF9GQhAmEgoKBkFJ",
            "Ul9GQRAnEgoKBkFJUl9GQhAoEgoKBkFJUl9VQRApEgoKBkFJUl9VQhAqEhEK",
            "DVNUQU5EX0RfREZfRkEQKxIRCg1TVEFORF9EX0RGX0ZCECwSEQoNU1RBTkRf",
            "Rl9EX0RGQRAtEhEKDVNUQU5EX0ZfRF9ERkIQLhIRCg1TVEFORF9EX0RCX0JB",
            "EC8SEQoNU1RBTkRfRF9EQl9CQhAwEg8KC0FJUl9EX0RGX0ZBEDESDwoLQUlS",
            "X0RfREZfRkIQMhIPCgtBSVJfRl9EX0RGQRAzEg8KC0FJUl9GX0RfREZCEDQS",
            "DwoLQUlSX0RfREJfQkEQNRIPCgtBSVJfRF9EQl9CQhA2EhEKDVNUQU5EX0Rf",
            "REZfRkMQN0IdqgIaRGFyZUZpZ2h0aW5nSUNFLkdycGMuUHJvdG9iBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DareFightingICE.Grpc.Proto.GrpcStatusCode), typeof(global::DareFightingICE.Grpc.Proto.GrpcFlag), typeof(global::DareFightingICE.Grpc.Proto.GrpcState), typeof(global::DareFightingICE.Grpc.Proto.GrpcAction), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GrpcStatusCode {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    [pbr::OriginalName("FAILED")] Failed = 1,
  }

  public enum GrpcFlag {
    [pbr::OriginalName("EMPTY")] Empty = 0,
    [pbr::OriginalName("INITIALIZE")] Initialize = 1,
    [pbr::OriginalName("PROCESSING")] Processing = 2,
    [pbr::OriginalName("ROUND_END")] RoundEnd = 3,
    [pbr::OriginalName("GAME_END")] GameEnd = 4,
  }

  public enum GrpcState {
    [pbr::OriginalName("STAND_STATE")] StandState = 0,
    [pbr::OriginalName("CROUCH_STATE")] CrouchState = 1,
    [pbr::OriginalName("AIR_STATE")] AirState = 2,
    [pbr::OriginalName("DOWN_STATE")] DownState = 3,
  }

  public enum GrpcAction {
    [pbr::OriginalName("NEUTRAL")] Neutral = 0,
    [pbr::OriginalName("STAND")] Stand = 1,
    [pbr::OriginalName("FORWARD_WALK")] ForwardWalk = 2,
    [pbr::OriginalName("DASH")] Dash = 3,
    [pbr::OriginalName("BACK_STEP")] BackStep = 4,
    [pbr::OriginalName("CROUCH")] Crouch = 5,
    [pbr::OriginalName("JUMP")] Jump = 6,
    [pbr::OriginalName("FOR_JUMP")] ForJump = 7,
    [pbr::OriginalName("BACK_JUMP")] BackJump = 8,
    [pbr::OriginalName("AIR")] Air = 9,
    [pbr::OriginalName("STAND_GUARD")] StandGuard = 10,
    [pbr::OriginalName("CROUCH_GUARD")] CrouchGuard = 11,
    [pbr::OriginalName("AIR_GUARD")] AirGuard = 12,
    [pbr::OriginalName("STAND_GUARD_RECOV")] StandGuardRecov = 13,
    [pbr::OriginalName("CROUCH_GUARD_RECOV")] CrouchGuardRecov = 14,
    [pbr::OriginalName("AIR_GUARD_RECOV")] AirGuardRecov = 15,
    [pbr::OriginalName("STAND_RECOV")] StandRecov = 16,
    [pbr::OriginalName("CROUCH_RECOV")] CrouchRecov = 17,
    [pbr::OriginalName("AIR_RECOV")] AirRecov = 18,
    [pbr::OriginalName("CHANGE_DOWN")] ChangeDown = 19,
    [pbr::OriginalName("DOWN")] Down = 20,
    [pbr::OriginalName("RISE")] Rise = 21,
    [pbr::OriginalName("LANDING")] Landing = 22,
    [pbr::OriginalName("THROW_A")] ThrowA = 23,
    [pbr::OriginalName("THROW_B")] ThrowB = 24,
    [pbr::OriginalName("THROW_HIT")] ThrowHit = 25,
    [pbr::OriginalName("THROW_SUFFER")] ThrowSuffer = 26,
    [pbr::OriginalName("STAND_A")] StandA = 27,
    [pbr::OriginalName("STAND_B")] StandB = 28,
    [pbr::OriginalName("CROUCH_A")] CrouchA = 29,
    [pbr::OriginalName("CROUCH_B")] CrouchB = 30,
    [pbr::OriginalName("AIR_A")] AirA = 31,
    [pbr::OriginalName("AIR_B")] AirB = 32,
    [pbr::OriginalName("AIR_DA")] AirDa = 33,
    [pbr::OriginalName("AIR_DB")] AirDb = 34,
    [pbr::OriginalName("STAND_FA")] StandFa = 35,
    [pbr::OriginalName("STAND_FB")] StandFb = 36,
    [pbr::OriginalName("CROUCH_FA")] CrouchFa = 37,
    [pbr::OriginalName("CROUCH_FB")] CrouchFb = 38,
    [pbr::OriginalName("AIR_FA")] AirFa = 39,
    [pbr::OriginalName("AIR_FB")] AirFb = 40,
    [pbr::OriginalName("AIR_UA")] AirUa = 41,
    [pbr::OriginalName("AIR_UB")] AirUb = 42,
    [pbr::OriginalName("STAND_D_DF_FA")] StandDDfFa = 43,
    [pbr::OriginalName("STAND_D_DF_FB")] StandDDfFb = 44,
    [pbr::OriginalName("STAND_F_D_DFA")] StandFDDfa = 45,
    [pbr::OriginalName("STAND_F_D_DFB")] StandFDDfb = 46,
    [pbr::OriginalName("STAND_D_DB_BA")] StandDDbBa = 47,
    [pbr::OriginalName("STAND_D_DB_BB")] StandDDbBb = 48,
    [pbr::OriginalName("AIR_D_DF_FA")] AirDDfFa = 49,
    [pbr::OriginalName("AIR_D_DF_FB")] AirDDfFb = 50,
    [pbr::OriginalName("AIR_F_D_DFA")] AirFDDfa = 51,
    [pbr::OriginalName("AIR_F_D_DFB")] AirFDDfb = 52,
    [pbr::OriginalName("AIR_D_DB_BA")] AirDDbBa = 53,
    [pbr::OriginalName("AIR_D_DB_BB")] AirDDbBb = 54,
    [pbr::OriginalName("STAND_D_DF_FC")] StandDDfFc = 55,
  }

  #endregion

}

#endregion Designer generated code
